from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]

def create_directorate(name: str):
    slug = name.lower().replace(" ", "_").replace("-", "_")

    paths = [
        BASE_DIR / "backend" / "api" / f"{slug}.py",
        BASE_DIR / "backend" / "services" / f"{slug}_service.py",
        BASE_DIR / "backend" / "agents" / f"{slug}_agent.py",
        BASE_DIR / "docs" / f"{slug}.md",
        BASE_DIR / "tests" / f"test_{slug}.py",
    ]

    for path in paths:
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(f"# {name} Directorate\n\nGenerated by Salus Forge.\n")

    return {
        "directorate": name,
        "slug": slug,
        "files_created": [str(p.relative_to(BASE_DIR)) for p in paths],
    }
