API_TEMPLATE = '''from fastapi import APIRouter

router = APIRouter(prefix="/{slug}", tags=["{title}"])

@router.get("/status")
def status():
    return {{
        "directorate": "{title}",
        "status": "operational",
        "version": "0.1.0"
    }}
'''

SERVICE_TEMPLATE = '''def get_status():
    return {{
        "status": "operational",
        "message": "{title} service online"
    }}
'''

AGENT_TEMPLATE = '''AGENT = {{
    "name": "{title} Agent",
    "mission": "Support the {title} Directorate.",
    "status": "active"
}}
'''

DOC_TEMPLATE = '''# {title} Directorate

Generated by Salus Forge.

## Mission
Support Project Salus operations for {title}.

## Status
Operational scaffold created.
'''

TEST_TEMPLATE = '''def test_{slug}_placeholder():
    assert True
'''
