API_TEMPLATE = '''from fastapi import APIRouter

router = APIRouter(prefix="/{slug}", tags=["{title}"])


@router.get("/status")
def status():
    return {{
        "directorate": "{title}",
        "status": "operational",
        "version": "0.1.0",
    }}
'''

SERVICE_TEMPLATE = '''class {class_name}Service:
    def get_status(self):
        return {{
            "status": "operational",
            "message": "{title} service online",
        }}
'''

AGENT_TEMPLATE = '''from dataclasses import dataclass


@dataclass
class {class_name}Agent:
    name: str = "{title} Agent"
    mission: str = "Support the {title} Directorate."
    status: str = "active"


AGENT = {class_name}Agent()
'''

DIRECTORATE_PACKAGE_INIT_TEMPLATE = '''from .agent import {class_name}Agent
from .api import {class_name}DirectorateAPI
from .memory import {class_name}Memory
from .models import {class_name}Model
from .prompts import {class_name}Prompts
from .service import {class_name}Service
from backend.directorates.base import Directorate


class {class_name}Directorate(Directorate):
    NAME = "{title} Directorate"

    def status(self):
        return "Operational"

    def objectives(self):
        return [
            "Advance mission readiness",
            "Improve resilience",
            "Support automation",
        ]

    def report(self):
        return {{
            "mission": "Support {title} operations.",
            "status": "Operational",
        }}
'''

DIRECTORATE_AGENT_TEMPLATE = '''from dataclasses import dataclass


@dataclass
class {class_name}Agent:
    name: str = "{title} Agent"
    mission: str = "Support the {title} Directorate."
    status: str = "active"
'''

DIRECTORATE_SERVICE_TEMPLATE = '''class {class_name}Service:
    def get_status(self):
        return {{
            "status": "operational",
            "message": "{title} service online",
        }}
'''

DIRECTORATE_API_TEMPLATE = '''from fastapi import APIRouter

router = APIRouter(prefix="/{slug}", tags=["{title}"])


@router.get("/status")
def status():
    return {{
        "directorate": "{title}",
        "status": "operational",
        "version": "0.1.0",
    }}
'''

DIRECTORATE_MODELS_TEMPLATE = '''from dataclasses import dataclass


@dataclass
class {class_name}Model:
    directorate: str = "{title}"
    status: str = "active"
'''

DIRECTORATE_MEMORY_TEMPLATE = '''class {class_name}Memory:
    def __init__(self):
        self.entries = []

    def add(self, entry: str) -> None:
        self.entries.append(entry)
'''

DIRECTORATE_PROMPTS_TEMPLATE = '''class {class_name}Prompts:
    def welcome(self) -> str:
        return "Welcome to the {title} Directorate."
'''

DIRECTORATE_MANIFEST_TEMPLATE = '''{{
  "name": "{title}",
  "version": "0.1.0",
  "dependencies": ["fastapi"],
  "permissions": ["read", "write"],
  "APIs": ["/{slug}/status"],
  "health_status": "operational"
}}
'''

DIRECTORATE_DOC_TEMPLATE = '''# {title} Directorate

Generated by Salus Forge.

## Mission
Support Project Salus operations for {title}.

## Status
Operational scaffold created.
'''

DIRECTORATE_TEST_TEMPLATE = '''def test_{slug}_placeholder():
    assert True
'''

REGISTRY_TEMPLATE = '''from backend.directorates.base import Directorate
from backend.directorates.{slug} import {class_name}Directorate

DIRECTORATES = {{
    "{title}": {class_name}Directorate,
}}
'''

DOC_TEMPLATE = '''# {title} Directorate

Generated by Salus Forge.

## Mission
Support Project Salus operations for {title}.

## Status
Operational scaffold created.
'''

TEST_TEMPLATE = '''def test_{slug}_placeholder():
    assert True
'''
